# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---

Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.scb.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &ordererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ordererOrg

        # ID to load the MSP definition as
        ID: ordererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/scb.com/msp

    - &producer
        Name: producerMSP
        ID: producerMSP

        MSPDir: crypto-config/peerOrganizations/producer.scb.com/msp
        AnchorPeers:
            - Host: peer0.producer.scb.com
              Port: 7051

    - &supplier
        Name: supplierMSP
        ID: supplierMSP

        MSPDir: crypto-config/peerOrganizations/supplier.scb.com/msp

        AnchorPeers:
            - Host: peer0.supplier.scb.com
              Port: 7051

    - &regulator
        Name: regulatorMSP
        ID: regulatorMSP

        MSPDir: crypto-config/peerOrganizations/regulator.scb.com/msp

        AnchorPeers:
            - Host: peer0.regulator.scb.com
              Port: 7051

    - &consumer
        Name: consumerMSP
        ID: consumerMSP

        MSPDir: crypto-config/peerOrganizations/consumer.scb.com/msp

        AnchorPeers:
            - Host: peer0.consumer.scb.com
              Port: 7051

Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

Profiles:

    SupplyChainOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *ordererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *producer
                    - *supplier
                    - *consumer
                    - *regulator
    SupplyChainOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *producer
                - *supplier
                - *consumer
                - *regulator
