OrdererOrgs:
  - Name: orderer
    Domain: scb.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: producer
    Domain: producer.scb.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: supplier
    Domain: supplier.scb.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: regulator
    Domain: regulator.scb.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: consumer
    Domain: consumer.scb.com
    Template:
      Count: 1
    Users:
      Count: 1
