
version: '2'

networks:
  scb:

services:
  orderer.supply-chain-blockchain.com:
    container_name: orderer.supply-chain-blockchain.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/supply-chain-blockchain.com/orderers/orderer.supply-chain-blockchain.com/:/etc/hyperledger/msp/orderer
        - ./channel-artifacts/genesis.block:/etc/hyperledger/configtx/genesis.block
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    networks:
      - scb

  ca.producer.supply-chain-blockchain.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.producer.supply-chain-blockchain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.supply-chain-blockchain.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b5880f0cd19b37b7b15ab41cedbf17ae922ef368dfbde85c8015df3ecaabb5d1_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/producer.supply-chain-blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    container_name: ca.producer.supply-chain-blockchain.com
    networks:
      - scb

  ca.supplier.supply-chain-blockchain.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.supplier.supply-chain-blockchain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supplier.supply-chain-blockchain.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/38be0871b19bdea1fc414dba019d91cee570a386b4c62def6a7fc7b2c45d9611_sk
    ports:
      - "7055:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/supplier.supply-chain-blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    container_name: ca.supplier.supply-chain-blockchain.com
    networks:
      - scb

  ca.regulator.supply-chain-blockchain.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.regulator.supply-chain-blockchain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regulator.supply-chain-blockchain.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3b18cd64b7ec6ad61a9a7f4aedd85fb5e2ce0ac2a6fbcddf4f1f3e49022c2fa6_sk
    ports:
      - "7056:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/regulator.supply-chain-blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    container_name: ca.regulator.supply-chain-blockchain.com
    networks:
      - scb

  ca.consumer.supply-chain-blockchain.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.consumer.supply-chain-blockchain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.consumer.supply-chain-blockchain.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c12e2e702ccef00475175b8512f87208583921120346113851bf605d607e81a1_sk
    ports:
      - "7057:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/consumer.supply-chain-blockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    container_name: ca.consumer.supply-chain-blockchain.com
    networks:
      - scb

  couchdb-producer:
    container_name: couchdb-producer
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - scb

  couchdb-consumer:
    container_name: couchdb-consumer
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5985:5984
    networks:
      - scb

  couchdb-regulator:
    container_name: couchdb-regulator
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5986:5984
    networks:
      - scb

  couchdb-supplier:
    container_name: couchdb-supplier
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5987:5984
    networks:
      - scb

  peer0.producer.supply-chain-blockchain.com:
    container_name: peer0.producer.supply-chain-blockchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.producer.supply-chain-blockchain.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=producerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.producer.supply-chain-blockchain.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_scb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-producer:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7061:7051
      - 7073:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/producer.supply-chain-blockchain.com/peers/peer0.producer.supply-chain-blockchain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/producer.supply-chain-blockchain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    depends_on:
      - orderer.supply-chain-blockchain.com
      - couchdb-producer
    networks:
      - scb

  peer0.regulator.supply-chain-blockchain.com:
    container_name: peer0.regulator.supply-chain-blockchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.regulator.supply-chain-blockchain.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=regulatorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.regulator.supply-chain-blockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_scb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-regulator:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7062:7051
      - 7074:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/regulator.supply-chain-blockchain.com/peers/peer0.regulator.supply-chain-blockchain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/regulator.supply-chain-blockchain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    depends_on:
      - orderer.supply-chain-blockchain.com
      - couchdb-regulator
    networks:
      - scb

  peer0.supplier.supply-chain-blockchain.com:
    container_name: peer0.supplier.supply-chain-blockchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.supplier.supply-chain-blockchain.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=supplierMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.supplier.supply-chain-blockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_scb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-supplier:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7063:7051
      - 7075:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/supplier.supply-chain-blockchain.com/peers/peer0.supplier.supply-chain-blockchain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/supplier.supply-chain-blockchain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    depends_on:
      - orderer.supply-chain-blockchain.com
      - couchdb-supplier
    networks:
      - scb

  peer0.consumer.supply-chain-blockchain.com:
    container_name: peer0.consumer.supply-chain-blockchain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.consumer.supply-chain-blockchain.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=consumerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.consumer.supply-chain-blockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_scb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-consumer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7064:7051
      - 7076:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consumer.supply-chain-blockchain.com/peers/peer0.consumer.supply-chain-blockchain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/consumer.supply-chain-blockchain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    depends_on:
      - orderer.supply-chain-blockchain.com
      - couchdb-consumer
    networks:
      - scb

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.consumer.supply-chain-blockchain.com:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/peer0.consumer.supply-chain-blockchain.com/users/Admin@peer0.consumer.supply-chain-blockchain.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/etc/hyperledger/configtx
        - ./channel-artifacts/channel.tx:/etc/hyperledger/configtx/channel.tx
    networks:
        - scb
